#!/usr/bin/env bash
set -euo pipefail
umask 077

readonly script_dir="$(
  cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1
  pwd -P
)"
# shellcheck source=scripts/lib/portable_runtime.sh
source "$script_dir/lib/portable_runtime.sh"

config_path="$(homecam_default_config_path)"
device_id=""
backend_url=""
source_token_file=""
force=false

usage() {
  cat <<'EOF'
Usage:
  configure_sim_device.sh [options]

Options:
  --config PATH       Output config path (default: XDG config home)
  --device-id ID      Backend-registered device id
  --backend-url URL   Deployed homecam backend URL
  --token-file PATH   Use an existing protected token file instead of prompting
  --force             Replace an existing config/token created at the target
  -h, --help          Show this help

The token is never accepted as a command-line argument. Without --token-file,
the script reads it from a hidden prompt and stores it with mode 600.
EOF
}

while (($# > 0)); do
  case "$1" in
    --config)
      (($# >= 2)) || { usage >&2; exit 2; }
      config_path="$2"
      shift 2
      ;;
    --device-id)
      (($# >= 2)) || { usage >&2; exit 2; }
      device_id="$2"
      shift 2
      ;;
    --backend-url)
      (($# >= 2)) || { usage >&2; exit 2; }
      backend_url="$2"
      shift 2
      ;;
    --token-file)
      (($# >= 2)) || { usage >&2; exit 2; }
      source_token_file="$2"
      shift 2
      ;;
    --force)
      force=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

config_path="$(realpath -m -- "$config_path")"
config_dir="$(dirname -- "$config_path")"
token_path="$config_dir/device.token"
token_temp=""
config_temp=""

if [[ -e "$config_path" && "$force" != true ]]; then
  homecam_die "configuration already exists: $config_path (use --force)"
  exit 1
fi

if [[ -z "$device_id" ]]; then
  read -rp 'Registered device id: ' device_id
fi
if [[ -z "$backend_url" ]]; then
  read -rp 'Homecam backend URL: ' backend_url
fi

HOMECAM_DEVICE_ID="$device_id"
HOMECAM_BACKEND_URL="$backend_url"
export HOMECAM_DEVICE_ID HOMECAM_BACKEND_URL
if [[ ! "$device_id" =~ ^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$ ]]; then
  homecam_die "invalid device id"
  exit 1
fi
if ! homecam_validate_backend_url "$backend_url"; then
  homecam_die "backend URL must be valid HTTPS (HTTP is loopback-only)"
  exit 1
fi

if [[ ! -d "$config_dir" ]]; then
  mkdir -p -- "$config_dir"
  chmod 700 -- "$config_dir"
fi
trap 'rm -f -- "${token_temp:-}" "${config_temp:-}"' EXIT

if [[ "$config_path" == "$token_path" && -z "$source_token_file" ]]; then
  homecam_die "configuration path and generated token path must be different"
  exit 1
fi

if [[ -n "$source_token_file" ]]; then
  source_token_file="$(realpath -- "$source_token_file")"
  if [[ "$source_token_file" == "$config_path" ]]; then
    homecam_die "configuration path and source token path must be different"
    exit 1
  fi
  if ! homecam_validate_device_token_file "$source_token_file"; then
    exit 1
  fi
  token_path="$source_token_file"
else
  if [[ -e "$token_path" && "$force" != true ]]; then
    homecam_die "token file already exists: $token_path (use --force)"
    exit 1
  fi
  read -rsp 'Device token: ' device_token
  printf '\n'
  if [[ ! "$device_token" =~ ^hc1\.[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89aAbB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}\.[0-9a-fA-F]{64}$ ]]; then
    unset device_token
    homecam_die "invalid device token format"
    exit 1
  fi
  token_temp="$(mktemp "$config_dir/.device.token.XXXXXX")"
  printf '%s' "$device_token" > "$token_temp"
  unset device_token
  chmod 600 -- "$token_temp"
  mv -f -- "$token_temp" "$token_path"
  token_temp=""
fi

config_temp="$(mktemp "$config_dir/.sim.env.XXXXXX")"
{
  printf '# Generated by configure_sim_device.sh; do not commit this file.\n'
  printf 'HOMECAM_DEVICE_ID=%s\n' "$device_id"
  printf 'HOMECAM_BACKEND_URL=%s\n' "$backend_url"
  printf 'HOMECAM_DEVICE_TOKEN_FILE=%s\n' "$token_path"
  printf 'HOMECAM_WORLD=small_house\n'
  printf 'HOMECAM_START_GAZEBO=true\n'
  # The browser is the primary viewer. Headless Gazebo avoids Qt/QML GUI
  # crashes taking down the required simulator process during long demos.
  printf 'HOMECAM_GAZEBO_GUI=false\n'
  printf 'HOMECAM_GAZEBO_HEADLESS=true\n'
  printf 'HOMECAM_MAP_STORE=\n'
  printf 'HOMECAM_MAP_WEB_HOST=127.0.0.1\n'
  printf 'HOMECAM_MAP_WEB_PORT=8765\n'
  printf 'HOMECAM_MAP_RVIZ=true\n'
  printf 'HOMECAM_CLOUD_MAP_ENABLED=true\n'
  printf 'HOMECAM_IMAGE_TOPIC=\n'
  printf 'HOMECAM_CAMERA_INFO_TOPIC=\n'
  printf 'HOMECAM_ODOM_TOPIC=/odom\n'
  printf 'HOMECAM_AUDIO_SOURCE=default\n'
  printf 'HOMECAM_AUDIO_SINK=default\n'
  printf 'HOMECAM_MICROPHONE_ENABLED=false\n'
  printf 'HOMECAM_MODEL_PATH=\n'
  printf 'HOMECAM_MONITORING_ENABLED=false\n'
  printf 'HOMECAM_TOPIC_TIMEOUT_SECONDS=90\n'
} > "$config_temp"
chmod 600 -- "$config_temp"
mv -f -- "$config_temp" "$config_path"
config_temp=""
trap - EXIT

HOMECAM_DEVICE_TOKEN_FILE="$token_path"
export HOMECAM_DEVICE_TOKEN_FILE
homecam_validate_device_config "$config_path"

homecam_log "device configuration created: $config_path"
homecam_log "token stored separately with mode 600: $token_path"
printf 'Run:\n  %q --config %q\n' \
  "$script_dir/run_gazebo_homecam.sh" "$config_path"
