"""Known results emitted by the capability implementations (not LLM guesses)."""


LABELS = {
    'navigate_to_pose': '목적지 이동', 'follow_person': '사람 따라가기',
    'patrol': '순찰', 'autoslam': '지도 만들기', 'relocalize': '위치 보정',
    'enroll_person': '얼굴 등록', 'get_weather': '날씨 조회',
    'set_weather_location': '날씨 지역 설정', 'manual_drive': '수동 조작',
    'fall_confirmation': '상황 확인',
}
ENDPOINTS = {
    'navigate_to_pose': '/navigate_to_pose', 'follow_person': '/follow_person',
    'patrol': '/patrol', 'autoslam': '/autoslam', 'relocalize': '/relocalize',
    'enroll_person': '/perception/person/enroll', 'get_weather': '/malbut/weather/get',
    'set_weather_location': '/malbut/weather/location/set',
    'manual_drive': '/assisted_teleop', 'fall_confirmation': '/malbut/agent/confirm_situation',
}
# Each tuple is (audio suffix, exact reported message/code, Korean transcript).
FAILURES = {
    'patrol': [
        ('map_missing', 'Saved /map is not available', '저장된 지도를 받지 못했어요.'),
        ('map_invalid', 'Saved /map is empty or invalid', '저장된 지도가 올바르지 않아요.'),
        ('camera_setup', 'RGB image and calibrated CameraInfo are required',
         '카메라 영상이나 보정 정보를 확인하지 못했어요.'),
        ('camera_stale', 'RGB camera is stale', '카메라 영상이 제때 들어오지 않아요.'),
        ('costmap_stale', 'Global costmap is not available or stale',
         '최신 장애물 지도를 확인하지 못했어요.'),
        ('map_frame', 'Global costmap and saved map must use the same frame',
         '장애물 지도와 저장 지도의 좌표계가 달라요.'),
        ('nav_unavailable', 'Nav2 NavigateToPose and Spin servers must be active',
         '이동이나 회전 기능이 준비되지 않았어요.'),
        ('localization_missing', 'Robot localization TF is not available',
         '로봇의 현재 위치를 확인하지 못했어요.'),
        ('map_changed', 'Saved map changed; start a new patrol on that map',
         '실행 중 지도가 바뀌었어요. 새 지도에서 다시 요청해 주세요.'),
        ('camera_transform', 'No current camera frame with matching TF',
         '카메라 영상과 같은 시점의 위치 정보를 확인하지 못했어요.'),
        ('nav_timeout', 'Nav2 goal response timeout', '이동 요청의 응답 시간이 초과됐어요.'),
        ('cancel_unconfirmed', 'Nav2 did not confirm cancellation',
         '이동 취소 완료를 확인하지 못했어요.'),
        ('nav_canceled', 'Nav2 goal was canceled externally', '이동 요청이 외부에서 취소됐어요.'),
        ('coverage_shortfall', 'No usable untried viewpoint remains; partial coverage returned',
         '남은 관측 지점으로 이동할 수 없어 요청한 범위의 관측을 마치지 못했어요.'),
    ],
    'autoslam': [
        ('map_name', 'map_name must be a filename without a path or extension',
         '지도 이름에 경로나 확장자를 넣을 수 없어요.'),
        ('map_missing', 'waiting for a live SLAM map', '실시간 지도를 받지 못했어요.'),
        ('map_stale', 'SLAM map updates stopped', '실시간 지도 갱신이 중단됐어요.'),
        ('transform_stale', 'robot transform is stale or too far in the future',
         '로봇 위치 정보의 시간이 올바르지 않아요.'),
        ('position_invalid', 'robot position is not finite', '로봇 위치 값이 올바르지 않아요.'),
        ('plan_timeout', 'Nav2 path planning did not respond in time',
         '경로 계획 응답 시간이 초과됐어요.'),
        ('plan_rejected', 'Nav2 planner rejected the planning request', '경로 계획 요청이 거절됐어요.'),
        ('frame_changed', 'SLAM frame changed during navigation', '이동 중 지도 좌표계가 바뀌었어요.'),
        ('map_update_missing', 'SLAM did not publish a new map after navigation',
         '이동 후 갱신된 지도를 받지 못했어요.'),
        ('save_failed', 'Nav2 map saver failed', '지도를 파일로 저장하지 못했어요.'),
        ('save_missing', 'map saver returned without the expected map files',
         '지도 저장 후 필요한 파일을 확인하지 못했어요.'),
        ('save_unknown',
         'map save result is unconfirmed; check map files before restarting AutoSLAM',
         '지도 저장 결과를 확인하지 못했어요. 다시 실행하기 전에 저장 파일을 확인해 주세요.'),
        ('transform_invalid', 'robot transform is not finite', '로봇 좌표 변환 값이 올바르지 않아요.'),
        ('orientation_invalid', 'robot transform has an invalid quaternion',
         '로봇 방향 정보가 올바르지 않아요.'),
        ('nav_unavailable', 'waiting for Nav2 navigation/planner and map saver',
         '주행, 경로 계획 또는 지도 저장 기능이 준비되지 않았어요.'),
    ],
    'relocalize': [
        ('map_required', 'no saved map is selected', '저장된 지도를 먼저 선택해 주세요.'),
        ('amcl_inactive', 'AMCL is not active', '위치 추정 기능이 활성화되지 않았어요.'),
        ('map_missing', 'the selected map was not received on the map topic',
         '선택한 지도 데이터를 받지 못했어요.'),
        ('scan_stale', 'no recent LiDAR scan', '최신 라이다 측정값을 받지 못했어요.'),
        ('pose_invalid', 'initial_pose must be a finite pose in the map frame',
         '입력한 초기 위치나 좌표계가 올바르지 않아요.'),
        ('pose_timeout', 'AMCL did not report the corrected pose in time',
         '보정된 위치의 응답 시간이 초과됐어요.'),
        ('scan_missing', 'no LiDAR scan after the pose correction',
         '위치 보정 후 라이다 측정값을 받지 못했어요.'),
        ('pose_missing', 'AMCL reported no pose during the global search',
         '지도 전체를 탐색하는 동안 위치 추정값을 받지 못했어요.'),
        ('shutdown', 'relocalization server is shutting down', '위치 보정 기능이 종료 중이에요.'),
    ],
    'enroll_person': [
        ('camera_timeout', 'Camera registration timed out', '카메라로 얼굴을 확인하는 시간이 초과됐어요.'),
        ('overlapping_people', 'Registration target overlaps another person',
         '등록할 분이 다른 분과 겹쳐 보여요. 떨어져 서 주세요.'),
        ('multiple_people', 'Select one visible person for registration',
         '여러 분이 보여요. 등록할 분을 한 분만 선택해 주세요.'),
        ('face_count', 'Registration requires exactly one usable face',
         '등록할 얼굴을 하나만 선명하게 보여 주세요.'),
        ('model_mismatch', 'Registry uses a different face model', '등록부와 얼굴 인식 모델이 달라요.'),
        ('name_invalid', 'Name must contain 1 to 128 characters',
         '이름은 한 글자부터 백이십팔 글자까지 입력해 주세요.'),
        ('name_control', 'Name contains control characters', '이름에 사용할 수 없는 문자가 있어요.'),
        ('registry_changed', 'Registry changed; refresh first',
         '등록 정보가 변경됐어요. 새로 확인한 뒤 다시 요청해 주세요.'),
        ('person_missing', 'Registered person does not exist', '변경할 등록 정보가 존재하지 않아요.'),
        ('capacity', 'At most five people can be registered', '등록 가능한 다섯 명을 모두 등록했어요.'),
        ('duplicate_name', 'This registered name already exists', '같은 이름이 이미 등록되어 있어요.'),
        ('feature_numeric', 'Face feature must be numeric', '얼굴 특징이 올바른 숫자 형식이 아니에요.'),
        ('feature_invalid', 'Face feature is empty or non-finite',
         '추출된 얼굴 특징이 비어 있거나 올바르지 않아요.'),
        ('feature_zero', 'Face feature has zero magnitude', '얼굴 특징을 구분하지 못했어요.'),
        ('sample_count', 'Invalid number of face samples', '얼굴 특징의 개수가 올바르지 않아요.'),
        ('feature_dimensions', 'Face feature dimensions differ', '얼굴 특징의 형식이 서로 달라요.'),
        ('gallery_dimensions', 'Feature dimension differs from gallery',
         '추출한 얼굴 특징과 기존 등록부의 형식이 달라요.'),
        ('photo_format', 'Only JPEG and PNG images are accepted', '사진은 제이펙이나 피엔지 형식으로 보내 주세요.'),
        ('photo_size', 'Photo is empty or exceeds the upload limit', '사진이 비어 있거나 파일 크기가 너무 커요.'),
        ('photo_pixels', 'Photo dimensions exceed the pixel limit', '사진 해상도가 너무 높아요.'),
        ('photo_decode', 'Cannot decode photo', '사진을 읽을 수 없어요.'),
    ],
    'follow_person': [
        ('superseded', 'follow goal was superseded before execution', '실행 전에 다른 요청으로 바뀌었어요.'),
    ],
    'get_weather': [
        ('location_required', 'LOCATION_REQUIRED', '날씨를 확인할 지역을 먼저 알려주세요.'),
        ('timeout', 'TIMEOUT', '날씨 정보 응답 시간이 초과됐어요.'),
        ('invalid_data', 'INVALID_DATA', '받은 날씨 정보가 올바르지 않아요.'),
        ('fetch_failed', 'FETCH_FAILED', '날씨 정보를 받아오지 못했어요.'),
        ('auth_failed', 'KMA_AUTH_FAILED', '기상청 서비스 인증에 실패했어요.'),
        ('rate_limited', 'KMA_RATE_LIMITED',
         '기상청 조회 한도에 도달했어요. 잠시 후 다시 요청해 주세요.'),
        ('service_unavailable', 'KMA_UNAVAILABLE', '기상청 서비스에 연결하지 못했어요.'),
        ('shutdown', 'SHUTTING_DOWN', '날씨 조회 기능이 종료 중이에요.'),
    ],
    'set_weather_location': [
        ('fetch_failed', 'FETCH_FAILED', '지역을 검색하지 못했어요.'),
        ('result_invalid', 'INVALID_DATA', '지역 조회 결과가 올바르지 않아요.'),
        ('invalid_query', 'LOCATION_INVALID_QUERY', '시나 동 이름으로 지역을 알려주세요.'),
        ('lookup_failed', 'LOCATION_LOOKUP_FAILED', '지역을 검색하지 못했어요.'),
        ('lookup_timeout', 'LOCATION_TIMEOUT', '지역 검색 응답 시간이 초과됐어요.'),
        ('invalid_data', 'LOCATION_INVALID_DATA', '검색된 지역 정보가 올바르지 않아요.'),
        ('save_failed', 'LOCATION_SAVE_FAILED', '조회한 지역을 저장하지 못했어요.'),
        ('timeout', 'TIMEOUT', '지역 설정 응답 시간이 초과됐어요.'),
        ('shutdown', 'SHUTTING_DOWN', '지역 설정 기능이 종료 중이에요.'),
    ],
}
COMMON_FAILURES = [
    ('manager_map_required', 'select a saved map first; only mapping is available',
     '저장된 지도를 먼저 선택해 주세요.'),
    ('manager_mapping_required', 'switch to mapping first; a saved map is selected',
     '지도 만들기 모드로 먼저 전환해 주세요.'),
    ('manager_localization_switching', 'localization is switching; retry after it settles',
     '현재 위치를 확인 중이에요. 위치 확인 후 다시 요청해 주세요.'),
    ('manager_localization_error', 'localization is ERROR; retry after it settles',
     '현재 위치 추정에 오류가 있어 실행하지 못했어요.'),
    ('manager_preempted', 'mission preempted by a replacement request', '다른 요청으로 실행이 중단됐어요.'),
    ('manager_service_unavailable', 'Downstream Service is unavailable', '기능 실행 서비스에 연결하지 못했어요.'),
    ('manager_goal_rejected', 'Downstream Action server rejected the goal',
     '기능 실행 서버가 요청을 거절했어요.'),
    ('manager_shutdown', 'system manager is shutting down', '실행 관리자가 종료 중이에요.'),
    ('manager_shutdown_timeout', 'system manager shutdown timed out', '실행 관리자 종료 시간이 초과됐어요.'),
]
PREFIX_FAILURES = {
    'patrol': [('nav_communication', 'Nav2 communication failed: ', '이동 기능과 통신하지 못했어요.')],
    'autoslam': [
        ('map_exists', 'map already exists: ', '같은 이름의 지도가 있어요. 다른 이름을 사용해 주세요.'),
        ('plan_communication', 'Nav2 planning transport error: ', '경로 계획 기능과 통신하지 못했어요.'),
        ('nav_communication', 'Nav2 transport error: ', '이동 기능과 통신하지 못했어요.'),
        ('prerequisites', 'mapping prerequisites not ready: ', '지도 만들기에 필요한 기능이 준비되지 않았어요.'),
    ],
    'relocalize': [('lidar_transform', 'no LiDAR transform: ', '라이다 좌표 변환을 확인하지 못했어요.')],
}

# Relocalization emits these parameterized messages from a fixed list of operations.
for _label, _name in [('global localization', '전역 위치 탐색'), ('AMCL update', '위치 갱신')]:
    _suffix = _label.lower().replace(' ', '_')
    FAILURES['relocalize'].append((
        _suffix + '_unavailable', f'AMCL {_label} service is unavailable',
        f'{_name} 서비스를 사용할 수 없어요.'))
for _label, _name in [('global localization', '전역 위치 탐색'), ('AMCL update', '위치 갱신'),
                      ('Spin goal', '회전 요청'), ('Spin', '회전')]:
    FAILURES['relocalize'].append((
        _label.lower().replace(' ', '_') + '_timeout', f'{_label} did not finish in time',
        f'{_name} 시간이 초과됐어요.'))

FIXED_REPLIES = {
    'navigation.configuration_missing': '목적지 이동 설정을 확인할 수 없어 이동하지 않았어요.',
    'navigation.map_missing': '사용 중인 저장 지도를 확인할 수 없어 이동하지 않았어요.',
    'navigation.changed': '지도나 목적지 설정이 변경되어 이동하지 않았어요. 다시 말씀해 주세요.',
    'navigation.target_missing': '저장된 지도에서 그 목적지를 확인하지 못했어요. 등록된 목적지 이름을 포함해 이동 요청을 다시 말씀해 주세요.',
    'operation.submit_unknown': '실행 요청의 상태를 확인할 수 없어요. 시작 요청을 다시 보내지는 않았어요.',
    'operation.guard_failed': '요청 조건을 확인할 수 없어 요청을 보내지 않았어요.',
    'operation.submitted': '실행 요청을 보냈어요. 접수 결과를 확인할게요.',
    'cancel.no_active_mission': '음성으로 요청한 실행 중인 동작이 없어요.',
    'cancel.requested': '음성으로 요청한 동작의 취소를 요청했어요. 종료 여부를 확인할게요.',
    'cancel.unknown': '음성으로 요청한 동작의 취소를 요청했지만 접수 여부를 확인하지 못했어요. 종료된 것으로 판단하지 않을게요.',
    'cancel.foreground_requested': '전면 작업의 취소를 요청했어요. 종료 여부를 확인할게요.',
    'cancel.foreground_none': '현재 실행 중이거나 대기 중인 전면 작업이 없어요.',
    'cancel.foreground_unknown': '전면 작업의 취소를 요청했지만 접수 여부를 확인하지 못했어요. 종료된 것으로 판단하지 않을게요.',
    'enrollment.unavailable': '얼굴 등록 기능을 준비하지 못했어요. 잠시 후 다시 시도해 주세요.',
    'enrollment.start_failed': '등록 요청을 시작하지 못했어요.',
    'enrollment.result_unknown': '등록 처리 결과를 확인하지 못했어요. 잠시 후 다시 시도해 주세요.',
    'enrollment.target_missing': '등록할 분을 확인하지 못했어요. 카메라 앞에서 한 분씩 말씀해 주세요.',
    'weather.unavailable': '지금 날씨 조회 기능을 사용할 수 없어요.',
    'weather.location_not_found': '지역을 찾지 못했어요. 시·구·동을 더 자세히 알려주세요.',
    'weather.location_failed': '날씨 조회 위치를 저장하지 못했어요. 잠시 후 다시 알려주세요.',
}
