<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>malbut_gazebo_plugins</name>
  <version>0.1.0</version>
  <description>Small Gazebo Fortress systems used by Malbut simulations.</description>
  <maintainer email="sanggeunji0117@gmail.com">SANGGEUN JI</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ignition-gazebo6</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
